// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc9SOV2lNPlW19YOlUgVRd_rw3wNHUVmg',
    appId: '1:906825370718:web:1c8ee542d55edb6f98f8cf',
    messagingSenderId: '906825370718',
    projectId: 'larasestoree',
    authDomain: 'larasestoree.firebaseapp.com',
    storageBucket: 'larasestoree.firebasestorage.app',
    measurementId: 'G-KHX5RGFYV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdijELWPgeHWB4vh0aIM8hCJLCzaaYVEQ',
    appId: '1:906825370718:android:89e0459a8542b5d598f8cf',
    messagingSenderId: '906825370718',
    projectId: 'larasestoree',
    storageBucket: 'larasestoree.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_k_lO-Wizy33TJb-61rQM5adxy1UiICg',
    appId: '1:906825370718:ios:3afd64b1bf466e1798f8cf',
    messagingSenderId: '906825370718',
    projectId: 'larasestoree',
    storageBucket: 'larasestoree.firebasestorage.app',
    iosBundleId: 'com.example.laStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc9SOV2lNPlW19YOlUgVRd_rw3wNHUVmg',
    appId: '1:906825370718:web:1c8ee542d55edb6f98f8cf',
    messagingSenderId: '906825370718',
    projectId: 'larasestoree',
    authDomain: 'larasestoree.firebaseapp.com',
    storageBucket: 'larasestoree.firebasestorage.app',
    measurementId: 'G-KHX5RGFYV0',
  );
}
